# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ruchin Patel
email: ruchinpa@usc.edu | 432-266-2949
description: ruchinpa@usc.edu | 432-266-2949
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  ruchin33
linkedin_username: ruchin-patel

# Build settings
markdown: kramdown
